version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    pull-request-branch-name:
      separator: '-'
    labels:
      - dependencies
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "11:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    labels:
      - dependencies
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: org.modelmapper:modelmapper
        versions:
          - 2.3.9
          - 2.4.0
          - 2.4.1
      - dependency-name: org.springframework.boot:spring-boot-starter-parent
        versions:
          - 2.4.2
          - 2.4.3
          - 2.4.4
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    target-branch: master
